### ISSUE TITLE
Compile time / cargo check time

### ISSUE THREAD

**Issue by clemens-msupply** [graphql-rust/juniper#1019]
We are currently using async graphql for our project and doing a `cargo check` takes quite a long time (up to ~25s). For my taste this is way to long and makes developing graphql endpoints quite painful. After some profiling it seems that the source of the problem is the amount of code that is generated by async graphql macros...

My question is, would I expect similar `cargo check` times with juniper? do you know any example projects that have a medium sized/large graphql schema which I could try?

**Comment by tyranron** [comment]
@clemens-msupply 

> My question is, would I expect similar cargo check times with `juniper`? 

This should be even worse, because we're generating more code by macros, and are going to generate even more.

This is a tradeoff, though. Generating such amount of code allows us to encode quite good and wise static checks, so the wrong schemas won't compile, instead of the code just panicking in runtime. So we sell compile times for better compile-time verified correctness. This is our choice.

> do you know any example projects that have a medium sized/large graphql schema which I could try?

I'm not aware of such open projects.

**Comment by clemens-msupply** [comment]
thanks you for your answer! I hope that `cargo check` becomes faster one day :-) I will experiment a little by splitting Query and Mutations into multiple structs so that the compiler hopefully can cache some previous check results...
