### ISSUE TITLE
Add graphql-ws support in light of subscriptions-transport-ws deprecation

### ISSUE THREAD

**Issue by bglw** [graphql-rust/juniper#1022]
This was mentioned in #896 but declined at that point. Since then, however, the winds of change have blown in favor of `graphql-ws`. The [graphql-ws protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) differs from Apollo's original [subscriptions-transport-ws protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md), and Apollo are [soon to archive their protocol and are now recommending use of graphql-ws](https://github.com/apollographql/subscriptions-transport-ws).

There is already some friction, as [graphql-ws-client](https://github.com/obmarg/graphql-ws-client) (and most ws clients coming out) only support the new protocol, while juniper only supports the old.

**Comment by tyranron** [comment]
@bglw thanks. We have plans to support both versions for the next major release.

**Comment by vincenzopalazzo** [comment]
@tyranron this feature is landed? :) was thinking that maybe I can be a good mentee? because I would like to have this feature

**Comment by tyranron** [comment]
@vincenzopalazzo nope, haven't touched it yet. Would like to see a PR from you, if you're willing to. As for design, I think it should be feature-gated in the existing crate. Thanks.

**Comment by LegendL3n** [comment]
Is juniper using `graphql-ws`? I saw this [workaround](https://github.com/graphql-rust/juniper/blob/master/examples/warp_subscriptions/src/main.rs) that came from this [PR](https://github.com/graphql-rust/juniper/pull/583), so I thought juniper was already in `graphql-ws`.

However, I receive `{"type":"ka"}` messages, which isn't from that protocol AFAIK.

**Comment by vincenzopalazzo** [comment]
@LegendL3n I think the new protocol graphql-ws is still not supported, I was planning to add it in the next few months

**Comment by LegendL3n** [comment]
Indeed.. Just saw on the README, that example really confused me 😅

**Comment by ccbrown** [comment]
I recently implemented the new protocol for another Go library, and could knock it out pretty quick here. It's fundamentally the same, but with some slight name changes and pings instead of keep-alives.

The worst part of it is just the naming of the protocol and libraries. The old protocol used the "graphql-ws" WebSocket subprotocol. Now, confusingly, the new protocol's reference implementation is a library called "graphql-ws". But it uses the "graphql-transport-ws" subprotocol. So I think the least confusing way to go about this is to forget about what the reference implementation is called, and organize based on the subprotocol name here.

So the new implementation can go into a new crate named `juniper_graphql_transport_ws`. And then in request routing, users can serve WebSocket requests using either the old `juniper_graphql_ws` or the new `juniper_graphql_transport_ws` crates based on subprotocol negotiation.

**Comment by allen-pattern** [comment]
Hello, is there any update here? Anything we can do to help see this feature rolled out?

**Comment by ccbrown** [comment]
> Hello, is there any update here? Anything we can do to help see this feature rolled out?

@allen-pattern There's an implementation in the pull request here: https://github.com/graphql-rust/juniper/pull/1158

If you'd like to help, you can:

- Leave comments on the PR. Does the PR meet your needs? Any thoughts on the API / crate changes?
- Give the PR a try and let us know how it works for you.

**Comment by chris-pattern** [comment]
Hi it looks like this was merged but I don't see the crate showing up on crates.io.  Is there a plan for when it will be released?
