### ISSUE TITLE
Returning GraphQLObject values without cloning

### ISSUE THREAD

**Issue by ClementNerma** [graphql-rust/juniper#1049]
I currently have a Rocket server from which GraphQL returns data using its context.

Many data inside use strings so my types do not implement `Copy`, only `Clone`.

The problem is that, when I return them from the state, I need to clone them before they're actually handled by GraphQL and converted again. Here is an example:

```rust
impl QueryRoot {
  async fn get_fingerprint(ctx: &GraphQLContext) -> Fingerprint {
    // ctx.data is an Arc<tokio::sync::RwLock<Data>>
    ctx.data.read().await.fingerprint.clone() // I'd like to remove the .clone() as GraphQL will convert this data anyway
  }
}
```

How can I do this?

**Comment by tyranron** [comment]
@ClementNerma this issue has nothing with the `juniper` itself. It's reproducible the same way in a regular Rust code without using `juniper`.

The problem is that your `.read()` lock returns [`RwLockReadGuard`] living to the end of the current scope only, and any references obtained from it cannot overlive it due to the Rust borrowing rules. So, __you cannot__ return a clean reference to the data inside `RwLock` at all for the term longer than  [`RwLockReadGuard`] lives.

Either you remove `RwLock` and redesign your code in the way that `GraphQLContext` contains datastructure allowing clean references to the inner `data`, or you are made to use `.clone()` with `RwLock`.

[`RwLockReadGuard`]: https://docs.rs/tokio/1/tokio/sync/struct.RwLockReadGuard.html

**Comment by ClementNerma** [comment]
This could have worked if the `#[graphql_object]` macro did some transformation behind the scene to make something like e.g.:

```rust
impl QueryRoot {
  async fn get_fingerprint(ctx: &GraphQLContext) -> GraphQLValue<Fingerprint> {
    graphql_convert_value(ctx.data.read().await.fingerprint)
  }
}
```

With the conversion happening in-place, we avoid the cost of cloning.

**Comment by ClementNerma** [comment]
It wouldn't bypass a thing, it would just convert the value to a string that could be transmitted over the network instead of converting it from the method's return value.

**Comment by tyranron** [comment]
@ClementNerma how it conceptually differ from `.clone()`? I cannot grasp.

**Comment by ClementNerma** [comment]
Currently, the method:
* Gets a value
* `.clone()` it
* Returns it
* And then Juniper analyzes it and attaches it to the response

With a wrapper like this, what would happen would be:
* The method gets a value
* Juniper analyzes it and attaches it to the reponse (no need for cloning here)
* And returns the transformed object directly

Do you see what I mean?

**Comment by ilslv** [comment]
@ClementNerma something like you want to achieve was already discussed in https://github.com/graphql-rust/juniper/issues/969

**Comment by ClementNerma** [comment]
Indeed, I didn't find this issue at first. Thanks!

**Comment by tyranron** [comment]
@ilslv despite the linked issue the idea of eager evaluation is quite insteresting.
```rust
impl QueryRoot {
  async fn get_fingerprint(ctx: &GraphQLContext) -> Eager<Fingerprint> {
    eager::eval(ctx.data.read().await.fingerprint)
  }
}
```

This, however, won't be so ergonomic, because `eager::eval()` will require context and selection set being passed explicitly to evaluate the iiner type in-place.
