### ISSUE TITLE
Arguments cannot handling patching correctly

### ISSUE THREAD

**Issue by thomas-jeepe** [graphql-rust/juniper#108]
In order to do a patching approach for updates, I need to know whether an argument is set to null or whether it has not set at all. For example implemented in javascript: https://medium.com/workflowgen/graphql-mutations-partial-updates-implementation-bff586bda989

I looked through the code and this seems to be the issue:

```rust
if let (&mut Some(ref mut args), &Some(ref meta_args)) = (&mut args, meta_args) {
            for arg in meta_args {
                if !args.contains_key(arg.name.as_str()) || args[arg.name.as_str()].is_null() {
                    if let Some(ref default_value) = arg.default_value {
                        args.insert(arg.name.as_str(), default_value.clone());
                    } else {
                        args.insert(arg.name.as_str(), InputValue::null());
                    }
                }
            }
}
```

From my understanding if there is no default argument, the value will be set to null. I'll fork it and simply remove that else statement.

**Comment by thomas-jeepe** [comment]
I made the fork and it seems to work now. I made two changes, I'll make a PR.

**Comment by mhallin** [comment]
Hello!

In order to implement this in Rust, you would need a counterpart to `Option<T>` with three states: value present, no value present, and no argument provided. Just removing that `else` clause will break query execution, which is why the tests in your PR are failing.

As an example, consider the following:

```rust
graphql_object!(Mutations: () |&self| {
    field setValue(field: Option<String>) -> i32 {
        // How do you check if the argument is null or not present here?
    }
});
```

**Comment by thomas-jeepe** [comment]
Yeah, in JS I suppose you have null, undefined and the value. That would have to mean a rework of optional args...

**Comment by Mange** [comment]
Lee Byron and friends (GraphQL designers and spec writers) recommend that you don't use null as a sentinel value for partial updates as most languages don't have the undefined/null distinction and because it limits implementors on how to treat values and objects/hashes.

We're using this method instead: (Excuse my brevity, I'm on my phone on a crowded bus)

```graphql
createPost(post: PostCreate) # Post
updatePost(id: ID!, updates: PostUpdates, deletes: PostDeletes) # Post

# Title and author are required, but the rest can be null.
PostCreate {
  title: String!,
  body: HTML,
  authorName: String!,
  categoryId: ID,
}

# All fields are optional in an update. If it's set here, change it in the database.
PostUpdates {
  title: String,
  body: HTML,
  authorName: String,
  categoryId: ID,
}

# You can unset body and category, but not title or author name as they
# were required.
PostDeletes {
  body: bool,
  categoryId: bool,
}

# Clear body and change title of post 42
updatePost(42, {title: "Short update"}, {body: true})
```

**Comment by thomas-jeepe** [comment]
That would work. It is slightly less pleasant to work with, however more explicit.

**Comment by theduke** [comment]
Closing this since it's not actionable for us.

There are ways to work around this distinction with schema design patterns, as mentioned above.
