### ISSUE TITLE
[juniper_rocket] Document GET request syntax

### ISSUE THREAD

**Issue by ysulyma** [graphql-rust/juniper#1098]
I am using the Juniper Rocket example. The POST endpoint and GraphiQL interface work for me, but I can't figure out how to send a GET request. (I'm also new to using Rocket.) I have tried

```
/graphql?{}
/graphql?request={}
/graphql?query={}
```
where {} is a URL-encoded version of
```
{
  __schema {
    types {
      name
    }
  }
}
```
and none of these work for me.

An explicit example of a GET request that works would be helpful.

**Comment by ilslv** [comment]
@ysulyma `/graphql?query` [should work](https://graphql.org/learn/serving-over-http/#get-request), but [`rocket` example](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper_rocket/examples/rocket_server.rs#L14-L21) is incorrect, as it uses `Deserialize` impl of [`GraphQLRequest`](https://docs.rs/juniper/latest/juniper/http/struct.GraphQLRequest.html). We'll address this in `0.16` release. 

Until then you have 2 options:
1. Use `POST` for both mutations and queries.
2. Implement custom structure with right `Deserialize` impl and convert this struct into a [`GraphQLRequest`](https://docs.rs/juniper/latest/juniper/http/struct.GraphQLRequest.html)

**Comment by tyranron** [comment]
> @ysulyma `/graphql?query` [should work](https://graphql.org/learn/serving-over-http/#get-request), but [`rocket` example](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper_rocket/examples/rocket_server.rs#L14-L21) is incorrect, as it uses `Deserialize` impl of [`GraphQLRequest`](https://docs.rs/juniper/latest/juniper/http/struct.GraphQLRequest.html).

This is not true. In [the specified example](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper_rocket/examples/rocket_server.rs#L14-L21) is used [`juniper_rocket::GraphQLRequest`](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper_rocket/src/lib.rs#L25-L28), rather than [`juniper::http::GraphQLRequest`](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper/src/http/mod.rs#L27-L45), and it doesn't implement `Deserialize` at all. In fact, it [implements `FromForm`](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper_rocket/src/lib.rs#L226-L287), which gives it [ability to being parsed from URL query strings](https://rocket.rs/v0.5/guide/requests/#query-strings). So all this works okay. Passing [`juniper::http::tests`](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper/src/http/mod.rs#L394-L398) confirms it.

The example, however, is really broken. Rather than having
```rust
#[rocket::get("/graphql?<request>")]
```
attribute, it should have
```rust
#[rocket::get("/graphql?<request..>")]
```

**Comment by tyranron** [comment]
@ysulyma the example was fixed, and now mentions the GET request query format:
https://github.com/graphql-rust/juniper/blob/bd8dc582a418f80d40a1b0ca969d3a6d4d77e2a6/juniper_rocket/examples/simple.rs#L29-L41
