### ISSUE TITLE
Interface  according to docs is failing to compile

### ISSUE THREAD

**Issue by Anderssorby** [graphql-rust/juniper#1104]
I'm having trouble implementing the cursor connections based pagination specification. https://relay.dev/graphql/connections.htm
My Node implementation is like this:

```rust
/// A node in a pagination query.
#[graphql_interface(for = [Company], scalar = juniper::DefaultScalarValue)]
pub trait Node {
  fn id(&self) -> String;
}
```

And company is like this:

```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Company {
  pub uuid: Uuid,
  pub name: String,
  #[serde(default)]
  pub users: Vec<ClientUserNoCompany>,
}

#[graphql_object(impl = [NodeValue], description = "A generic company")]
impl Company {
  pub fn id(&self) -> String { self.uuid.to_string() }
}
```
But I'm getting errors like this

```
 #[graphql_object(impl = [NodeValue], description = "A generic company")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `GraphQLInterface<__S>` is not implemented for `NodeValueEnum<Company>`
```

Why is this happening? Note: I'm using the master branch

**Comment by tyranron** [comment]
@Anderssorby the Book on the `master` branch is quite outdated, sorry for that. We're not going to update it now, because there are some more fundamental changes to happen. We're going to update it right before release.

But, the code docs in `juniper_codegen` crate [should be fine and correct](https://github.com/graphql-rust/juniper/blob/4b89d61f21fd15e0932e458b2011160977c51c0d/juniper_codegen/src/lib.rs#L867-L1294).

The problem with your example is in `scalar = juniper::DefaultScalarValue` attribute argument on the `Node` trait. By default, the derived implementations are abstracted over `ScalarValue` types via type parameter `__S: ScalarValue`, and you define the `Company` GraphQL object this way. On the other hand, the `Node` GraphQL interface is derived for `juniper::DefaultScalarValue` usage only, not for any `__S: ScalarValue`. That's why compilation fails. So:
1. either remove `scalar = juniper::DefaultScalarValue` attribute argument from the `Node` interface definition;
2. or add `scalar = juniper::DefaultScalarValue` attribute argument to the `Company` GraphQL object definition.

I'd recommend the option 1.

I'm trying to rework the whole traits machinery in #1072, so it will be much more flexible and polymorphic, without such gotchas. However, it needs quite a time to land.

**Comment by Anderssorby** [comment]
Thanks. Maybe there should be an explicit check and warning for this specific error.
