### ISSUE TITLE
Example to integrate with Axum

### ISSUE THREAD

**Issue by bakatest-me** [graphql-rust/juniper#1184]
Hi everyone i'm newbie in Rust (from Golang).  Juniper(Graphql) look very cool. 
Can you show me about example to integrate with Axum?

**Comment by kaos** [comment]
I think this is covered by #986

**Comment by tyranron** [comment]
The examples may be found [in `juniper_axum/examples`](https://github.com/graphql-rust/juniper/tree/761710205a5a928ce1d7be69894650059f91e877/juniper_axum/examples) and [in API docs](https://github.com/graphql-rust/juniper/blob/761710205a5a928ce1d7be69894650059f91e877/juniper_axum/src/subscriptions.rs) (not released yet, however).

**Comment by paulkre** [comment]
When will `juniper_axum` be released?

**Comment by paulkre** [comment]
The examples are pretty useless if you can't install the crate.

**Comment by LegNeato** [comment]
It's being worked on:

https://github.com/graphql-rust/juniper/milestone/4

**Comment by alexhancock** [comment]
Does anyone knowledgeable about cargo know if there is a way to temporarily depend on the crate in the git repo until it is published?

I read https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories, but suspect that because the top level of the https://github.com/graphql-rust/juniper has a `Cargo.toml`, it will auto-detect and use that as the dependency.

Is there a facility to specify the path _inside_ the git repo, and use that when resolving the dependencies?

**Comment by tyranron** [comment]
@alexhancock 

Something like this should work OK:
```toml
juniper = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
juniper_axum = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
```
