### ISSUE TITLE
Add hyper example/integration

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#119]
I would be great to have a juniper crate (or example) that integrates with "vanilla" hyper

**Comment by theduke** [comment]
We can definitely write up an example, probably using https://github.com/alexcrichton/futures-rs for executing the Juniper part.

I think vanilla Hyper might be  too edge case or to use-case specific to have an integration crate though.

**Comment by theduke** [comment]
PS: what I actually meant to link to was https://github.com/alexcrichton/futures-rs/tree/master/futures-cpupool

**Comment by LegNeato** [comment]
My thinking was we have Iron and Rocket integration, but generally don't leverage that many features of them as all the GraphQL queries are on one route and merely passed through to `juniper` via the framework. Most the stuff Juniper needs (status codes, http method, getting a query string, etc) is in `http`/`hyper`. For most standalone GraphQL services merely using Hyper+juniper would likely be sufficient without the added complexity or dependencies of a web framework.

**Comment by alexfedoseev** [comment]
@theduke @mhallin Does `juniper` work w/ `hyper@0.11.x`? All my attempts to run it failed due to lifetime issues and I'm not sure if it's me or it just doesn't supposed to work.

**Comment by alexfedoseev** [comment]
nvm, it worked

**Comment by dvic** [comment]
@theduke I have a first version of the hyper integration crate, which uses https://crates.io/crates/futures-cpupool to execute the request (so that the hyper threads are not blocked). It also includes a running example server. You can find it at:

https://github.com/dvic/juniper/tree/hyper-integration/juniper_hyper

It took me quite a while to get the lifetimes and references working because of the cpu pool. I'd love to receive feedback on the design. E.g., since Hyper does not include a router, it seemed more appropriate to expose public handler functions instead of a single Service implementation. What are your thoughts on this?

I still need to finish a few things:
* documentation
* properly rendering the errors (with correct status codes)
* tests

**Comment by LegNeato** [comment]
@dvic that looks great, thanks for working on this! I think the handler functions are sufficient. We could have an entire hyper service but I think it is more flexible the way you currently have it.

A couple of small things:

* Please add it to the main juniper README.
* It's awesome you added the playground! Please add a `graphiql` function as well to keep parity with the other integrations.
* I know you said tests are TBD...but I want to point out we have a http integration test harness you should plug into. For example, Rocket is using it here: https://github.com/graphql-rust/juniper/blob/master/juniper_rocket/src/lib.rs#L466.

Thanks again for digging into this! 🍻

**Comment by dvic** [comment]
@LegNeato I added the `graphiql` UI and also the http tests, thanks for the tip! I submitted a WIP PR #230 so discussion can take place there.

**Comment by LegNeato** [comment]
https://crates.io/crates/juniper_hyper has now been published! 🎉
