### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#1198]
It has been a while since we have done a new release. There are good bugfixes on master. We should release soon and not wait for the large refactor.

**Comment by tyranron** [comment]
@LegNeato not many things left. We have a [milestone](https://github.com/graphql-rust/juniper/milestone/4) for that.

However, the most work, not mentioned there, will take the Book rewrite, because it's too outdated.

**Comment by LegNeato** [comment]
Ah, I didn't see the milestone! Feel free to close this.

**Comment by tyranron** [comment]
@LegNeato now it's only the Book rework left!

**Comment by tyranron** [comment]
@davidpdrsn while reworking the Book in #1230, I've noticed that [`davidpdrsn/graphql-app-example`](https://github.com/davidpdrsn/graphql-app-example) sill dependends on `juniper` 0.14.

Would you mind adding me as a collaborator to `juniper-from-schema`, `juniper-eager-loading` and `davidpdrsn/graphql-app-example`, so I at least keep them up-to-date with latest `juniper` and its reworkings?

**Comment by Kinflou** [comment]
> @davidpdrsn while reworking the Book in #1230, I've noticed that [`davidpdrsn/graphql-app-example`](https://github.com/davidpdrsn/graphql-app-example) still dependends on `juniper` 0.14.
> 
> Would you mind adding me as a collaborator to `juniper-from-schema`, `juniper-eager-loading` and `davidpdrsn/graphql-app-example`, so I at least keep them up-to-date with the latest `juniper` and its reworkings?

@tyranron 
Since you want to be a collaborator i wonder if you already have some changes done on a `juniper-from-schema` fork or something similar?

I ask because i forked(https://github.com/Kinflou/juniper-from-schema) and started upgrading and reworking the crate, but i was unsure if i ask the author(\@davidpdrsn) if i could take over ([#juniper-from-schema/141](https://github.com/davidpdrsn/juniper-from-schema/issues/141)) or if i make a new fork/crate with my changes, since they are quite a few.

I'm up to collaboration on it

**Comment by tyranron** [comment]
@Kinflou wonderful! No, I haven't touched `juniper-from-schema` and its ecosystem yet, but I do plan too. Would like to review your PR and give feedback. However, we need @davidpdrsn for this.

I propose you to make a PR into the upstream once `juniper` 0.16 is released.

**Comment by Snoupix** [comment]
Hello @tyranron, hope you're doing fine.

I wanted to ask you if you have an ETA on the 0.16 release and if you needed help somewhere (I don't know the codebase but I still can try my best).

Much respect for your work
