### ISSUE TITLE
Allow reading the juniper request from juniper_rocket Request.

### ISSUE THREAD

**Issue by gabisurita** [graphql-rust/juniper#132]
I'm using `juniper`with `rocket` and I have a use case where I want to implement an Authorization layer based on the `operation_name`, but I can't read the `operation_name` from the `juniper_rocket::GraphQLRequest` because it doesn't expose `juniperd::GraphQLRequest`.

A quick fix would be make `juniper_rocket::GraphQLRequest` content public. A `Deref` would also be nice IMO. I can try to sketch a PR if you agree with this.

**Comment by theduke** [comment]
I would recommend to handle authentication in the rocket handler rather than in the resolvers, 
and put user information into the `Context`, maybe a:

```
struct Context {
   user: Option<User>,
}
```

For the login, I usually do it as a mutation that takes user/password as arguments and returns a token.

**Comment by WillSquire** [comment]
Isn't `Context` usually passed into Rocket's managed state? E.g:

```
rocket::ignite()
    .manage(Context {
      //...
    })
    .mount("/", routes![foo])
    .launch();
```

Unless I'm missing something here, wouldn't this set authentication state globally instead of ["Request-Local"](https://rocket.rs/guide/state/#request-local-state)? If anyone is reading this, this is definitely something one would **NOT** want to do

**Comment by theduke** [comment]
`Context` was refering to juniper's context, which can be constructed for each query, not rockets `State` feature.
