### ISSUE TITLE
Pass request data into context for authorisation

### ISSUE THREAD

**Issue by michalbe** [graphql-rust/juniper#373]
Hello.
I'm trying to add Auth0 support to my `Juniper` + `Rocket` setup. All I need to achieve is to pass proper `user_id` to the context so I can fetch & respond with data for the authenticated user if they pass token validation. 
I created proper request guard to retrieve the token from the headers, verify it and return `user_id` into the request handler, but since `Context` is being passed as a reference, I cannot modify it. And since it's a `Rocket::State` object, I cannot create a new one inside the handler and pass it down to `GraphQLResponse::execute`.  My current handler looks like that:

```rust
#[post("/graphql", data = "<request>")]
fn post_graphql_handler(
    context: State<Context>,
    request: juniper_rocket::GraphQLRequest,
    schema: State<Schema>,
    token: Token, // This is Auth0 claim struct
) -> juniper_rocket::GraphQLResponse {
    context.user_id = token.sub; // This obviously doesn't work because 
                                 // error[E0594]: "cannot assign to data in a `&` reference"
    request.execute(&schema, &context)
}
```

This is the first time I'm implementing something like that in Rust, and I ran out of ideas on how this should be done.

**Comment by davidpdrsn** [comment]
Instead of using `State` you should be able to implement [FromRequest](https://api.rocket.rs/v0.4/rocket/request/trait.FromRequest.html) for `Context`. That way your handler will get an owned `Context` which you’re then free to mutate. It does mean all your handlers wont share the same context but I guess that is fine.

This is what I do in the app I work on. For example in the `FromRequest` implementation for `Context` I also grab a database connection from a connection pool. The pool is stored in a `State`. I also check for authentication headers and set an `Option<CurrentUser>` sorta type.

**Comment by michalbe** [comment]
@davidpdrsn OMG this works, thanks! I haven't seen the simplest solution and it was always right before my eyes! Thank you Sir, and have a nice weekend!

**Comment by LegNeato** [comment]
It would be great to have some docs on this!

**Comment by michalbe** [comment]
Indeed. I have a feeling that `Rocket` isn't a first choice framework for people working with `Juniper`, it's way easier to find examples or docs on Iron. I'll try to change that once I'll feel comfortable enough to write something on the subject. Thanks for inspiration :)

**Comment by davidpdrsn** [comment]
@michalbe if you’re interested I maintain an example app that uses juniper and Rocket. You can find it here https://github.com/davidpdrsn/graphql-app-example

**Comment by folivi** [comment]
hi @michalbe 
can you please share your implementation?
