### ISSUE TITLE
Derive GraphQLInputObject for a type

### ISSUE THREAD

**Issue by jasonlor** [graphql-rust/juniper#458]
**Is your feature request related to a problem? Please describe.**
Trying to keep my code as minimal and maintainable as possible. I have some cases where I'm reusing the input object but differentiate by having different input function arguments. 

**Describe the solution you'd like**
- Allow GraphQLObject and GraphQLInputObject to be derived for types.

```
#[derive(GraphQLInputObject)]
pub type CreateThing1Input = CreateThingInput;

#[derive(GraphQLInputObject)]
pub type CreateThing2Input = CreateThingInput;

pub struct CreateThingInput {}

pub struct Thing1 {}
impl Thing1 {
  pub fn create(input: CreateThing1Input) {
    some_function(params: &input, thing_type: ThingType::Thing1);


```

**Comment by theduke** [comment]
Type aliases can't be treated as separate types due to how the type system works.

One possibility would be to allow a newtype derive like for [scalars](https://graphql-rust.github.io/juniper/current/types/scalars.html#newtype-pattern).

But I'm skeptical. If the type is the same, and assumed to evolve in the same way, then use the same type. I don't really see the value of having the types named differently.

It would also make it somewhat easier to break backwards compatibility guarantees when you decide you need to change one of the inputs.

So a probable wont-fix from my view.

You can always write a simple `macro_rules!` macro to achieve the same thing with minimal effort.

```rust
macro_rules! make_thing_input {
  ($name:ident) => {
     #[derive(GraphQLinputObject)]
     pub struct $ident { field1: bool }
  }
}

make_thing_input!( CreateThing1Input);
make_thing_input!( CreateThing2Input);
```

**Comment by jasonlor** [comment]
Makes sense, thanks!
