### ISSUE TITLE
Remove the From<Dispaly> trait for FieldError

### ISSUE THREAD

**Issue by david0u0** [graphql-rust/juniper#469]
**Is your feature request related to a problem? Please describe.**
This may be a wild, breaking change, but I found it error-prone for `FieldError` to implement `From<Display>` trait.

According to [the document](https://docs.rs/juniper/0.9.1/juniper/struct.FieldError.html#impl-From%3CT%3E), `FieldError` now implements `From<Display>` trait, which can transform anything implementing `Display` into `FieldError`. This is dangerous with the `?` operator.

For example, I may have something like
```rust
impl Mutation {
    fn some_mutation(context: &Ctx) -> Result<bool, FieldError> {
        do_the_mutation()?;  // Danger!!
        // Something else...
        Ok(true)
    }
}
fn do_the_mutation() -> Result<(), SuperSecretError> {
    // implementation
}
```
where `SuperSecretError` implements `Display` trait, and contains some critical information I don't like users to know.

However, when i use the `?` operator in `some_mutaion` function, rust will automatically transform `SuperSecretError` into `FieldError`, and send it to users. There __WON'T__ be any compile error or warning. Such transformation simply relies on `format!` macro.

As a backend programmer, I implement the `Display` trait for better logging, not for web users. The leakage of information is counter-intuitive. Even if there's no critical information leakage, such transformation is not what a programmer would expect.

**Describe the solution you'd like**
Remove the `From<Dispaly>` trait for `FieldError`

**Describe alternatives you've considered**
Now in my own project, I use the trait `IntoFieldError`, and strictly forbid anyone to use the raw `FieldError`.

We can document the danger of `FieldError` + `Display`, so people can still take advantage of such transformation, while it is encouraged not to do so.

**Comment by davidpdrsn** [comment]
I see what you're saying, however I think it makes sense to keep because of ergonomics. Users who want more control can use their own error type and implement `IntoFieldError`, like you're saying.

I think documenting the possible danger is a good idea. PRs for that very welcome 😊 

Relevant discussion can be found [here](https://github.com/graphql-rust/juniper/pull/419). There we ran into issues implementing `std::error::Error` for `FieldError` because of this, but eventually decided not to implement `std::error::Error` because we think the ergonomics of `From<Display>` are more valuable. I agree with that decision.

**Comment by LegNeato** [comment]
@davidpdrsn should this one be closed out?

**Comment by davidpdrsn** [comment]
Yep.
