### ISSUE TITLE
Unable to derive struct with &str

### ISSUE THREAD

**Issue by urkle** [graphql-rust/juniper#471]
**Describe the bug**
I receive an error 

`the trait `juniper::ast::FromInputValue<__S>` is not implemented for `&str``
when deriving a struct that users &str types.

**To Reproduce**
Insertable is from Diesel
```rust
#[derive(Insertable, juniper::GraphQLInputObject)]
#[table_name = "users"]
pub struct NewUser<'a> {
    pub name: &'a str,
    pub roles: Vec<&'a str>,
}
```

**Expected behavior**
Code to compile :)

**Additional context**
Related to issue #225

**Comment by cairomassimo** [comment]
AFAIK this is not possible because input string values have to be moved to the resolver, they cannot be passed by reference. Even if lifetime parameter are accepted (#225 was resolved), I don't think Juniper can do anything smarter for references in input objects. (A more expert Juniper developer may prove me wrong...)

Try changing all `&'a str` to `String`: Diesel `Insertable` should be able to handle that. Otherwise you should use two different structs for insertables and input objects.

**Comment by urkle** [comment]
@cairomassimo the more I'm learning how Rust works that seems to be the case.  I'm going to close this out.
