### ISSUE TITLE
trait FromContext::from return &Self

### ISSUE THREAD

**Issue by olvyko** [graphql-rust/juniper#475]
How can I implement conversion when I need to `return` reference?
Maybe I don’t understand something.
```rust
struct AContext {
    data: String,
}

struct BContext {
    data: String,
}

impl juniper::Context for AContext {}
impl juniper::Context for BContext {}

impl juniper::FromContext<AContext> for BContext {
    fn from(value: &AContext) -> &Self {
        // CAN'T return reference
        &BContext {
            data: value.data.clone(),
        }
    }
}
```
Just normal conversion trait:
```rust
pub trait From<T> {
    fn from(T) -> Self;
}
```
Juniper:
```rust
pub trait FromContext<T> {
    fn from(value: &T) -> &Self;
}
```

**Comment by LegNeato** [comment]
Happy to take a PR!

**Comment by davidpdrsn** [comment]
I have looked into this a bit and I think I see why we return `&Self`.

For most use cases you will use the same context throughout the schema. For those situations we have this implementation:

```rust
impl<T> FromContext<T> for T
where
    T: Context,
{
    fn from(value: &T) -> &Self {
        value
    }
}
```

If `FromContext::from` returned `Self` rather than `&Self` how would you implement this method? It still has to take `T` by reference (`&T`) because the executor only has a reference to the context. We also need to be able to call this method more than once.

We could require `where T: Context + Clone` and then implement it with `value.clone()`, however then we would be cloning the context all the time which doesn't seem ideal.

Because of this I think your only option is to nest your context types:

```rust
struct AContext {
    b: BContext,
    data_unique_to_a: Something,
}

struct BContext {
    data: String,
}

impl juniper::Context for AContext {}

impl juniper::Context for BContext {}

impl juniper::FromContext<AContext> for BContext {
    fn from(value: &AContext) -> &Self {
        &value.b
    }
}
```

This may or may not fit your use case, but it should compile.

**Comment by olvyko** [comment]
I think you can close this issue, OR we can look for another solution, maybe someone has a more elegant solution

**Comment by LegNeato** [comment]
I think nesting is the proper solution.
