### ISSUE TITLE
juniper_warp: panic when connection reset

### ISSUE THREAD

**Issue by spacemeowx2** [graphql-rust/juniper#589]
**Describe the bug**

thread 'tokio-runtime-worker' panicked at 'Websocket receive error: WebSocket protocol error: Connection reset without closing handshake', ...\.cargo\git\checkouts\juniper-aa5e857cd28538c7\cab6dec\juniper_warp\src\lib.rs:495:46

**To Reproduce**

Not sure. But I guess reset a connection when sending websocket frame could reproduce.

**Expected behavior**

Don't panic because one connection is reset.

**Additional context**

https://github.com/graphql-rust/juniper/blob/6e4bc127b05dc29f7832cbf468c9fb2bc18f78ec/juniper_warp/src/lib.rs#L495

**Comment by LegNeato** [comment]
@nWacky

**Comment by nWacky** [comment]
@spacemeowx2,

I looked it up.

For now it's unclear how to handle errors when dealing with channels. For now, it creates a new channel which returns all messages to end user and keeps executing logic inside `ForEach` future. Because `ForEach` expects return type of `Future<Output = ()>`, it's not possible to return errors in there => it's not possible to return errors for now (a potential workaround could be by implemeting custom future that drives iterator to completion). 

For now, I can change `juniper_warp`'s subscriptions impl so that it [ignores errors](https://github.com/nWacky/juniper/tree/improve-subscriptions)

**Comment by LegNeato** [comment]
Would an optional dependency using https://github.com/tokio-rs/async-stream help?

**Comment by spacemeowx2** [comment]
What about using [`fold`](https://docs.rs/futures/0.3.1/futures/stream/trait.StreamExt.html#method.fold) instead of `for_each`?

**Comment by nWacky** [comment]
`fold` worked, didn't think of it. 

#591 should resolve the issue
