### ISSUE TITLE
Support for `uuid` version `0.7` dropped

### ISSUE THREAD

**Issue by projektir** [graphql-rust/juniper#629]
`juniper` on `master` has moved to the `0.8` version of the `uuid` crate. One problem with that is a lot of other integrations only support `0.7`, most notably, the `diesel` PostgreSQL integration. As such, we still want to stay on `0.7`.

Is it possible to maintain support for both versions? `diesel` specifies a feature like `uuidv07`.

**Comment by projektir** [comment]
The actual implementation is rather small and works fine if I use it with the previous `uuid` type, so it's more just a matter of features to keep things tidy.

**Comment by LegNeato** [comment]
Sure, we would be able to specify a min as 7.0 as Cargo.toml accepts ranges. Patches welcome!

**Comment by Dylan-DPC** [comment]
Hi. Co-maintainer of uuid here. I wouldn't recommend support ranged versions. 0.7 UUID and 0.8 UUID are incompatible with each other, which means that there's no guarantee which one is used if you go with ranged versions. 
Secondly, with 0.8 being the active version, and work in progress towards a 1.0 release, we are no longer supporting 0.7 versions, so if future if anything breaks it could lead to awkward situations for your users. 
Supporting only the latest version, is a good strategy and I hope more crates go that route as well. We are discussing ways that can help this cases in the future so that crates may use the types across incompatible versions in a more compatible way if they are only using it as a data type. Thanks

**Comment by projektir** [comment]
I should add that I discovered that `diesel` apparently does support 0.8 with Postgres, it just wasn't obvious, so will be moving to that.

But in the future when there's a 1.0 release of `uuid` keep this in mind, it's potentially a breaking change for consumers.
