### ISSUE TITLE
Juniper Book (master) generation is not working.

### ISSUE THREAD

**Issue by kunjee17** [graphql-rust/juniper#679]
**Describe the bug**
Seems to book (master) generation issue.

**To Reproduce**
If you go to subscription page, you will find below text instead of plain old generated html. 

```
Currently there is an example of subscriptions with [warp][warp], but it still in an alpha state. GraphQL over [WS][WS] is not fully supported yet and is non-standard.

    Warp Subscription Example
    Small Example

[Coordinator]: https://docs.rs/juniper_subscriptions/0.15.0/struct.Coordinator.html [SubscriptionCoordinator]: https://docs.rs/juniper_subscriptions/0.15.0/trait.SubscriptionCoordinator.html [Connection]: https://docs.rs/juniper_subscriptions/0.15.0/struct.Connection.html [SubscriptionConnection]: https://docs.rs/juniper_subscriptions/0.15.0/trait.SubscriptionConnection.html [Future]: https://docs.rs/futures/0.3.4/futures/future/trait.Future.html [warp]: https://github.com/graphql-rust/juniper/tree/master/juniper_warp [WS]: https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md [GraphQLError]: https://docs.rs/juniper/0.14.2/juniper/enum.GraphQLError.html [Schema]: ../schema/schemas_and_mutations.md 
```

**Expected behavior**
It should have generated proper html

**Additional context**
I haven't checked other pages for issues. But best guess is it might be there and fixing one page should fix all pages.

**Comment by tyranron** [comment]
@kunjee17 yup, there is some mess around links.  I've planned to fix it eith the subscriptions layer being polished altogether. However, earlier PRs are still welcome 😉

**Comment by siyopao** [comment]
Hi! I think this has been fixed. (The links are still broken though.) When I do `mdbook build` in `docs/book` it seems to be fine:

<img width="1210" alt="Screen Shot 2020-07-06 at 10 02 10" src="https://user-images.githubusercontent.com/28915792/86546453-f4597580-bf6f-11ea-9372-6ff0157eaeda.png">

However, I had to add a title in `SUMMARY.md` otherwise it stopped generating content at `Type System: Other types: Union`. Did you not have this problem?
