### ISSUE TITLE
Wrong number of type arguments for Schema/RootNode

### ISSUE THREAD

**Issue by jaythomas** [graphql-rust/juniper#708]
(Apologies as I'm new to Rust and haven't been able to find avenues of help for this elsewhere.)

After upgrading Juniper to the latest version I am having an issues defining a type for my schema. I get the error message:

```
error[E0107]: wrong number of type arguments: expected at least 3, found 2
   --> src/graphql_schema.rs:210:19
    |
210 | pub type Schema = RootNode<'static, QueryRoot, EmptyMutation>; 
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected at least 3 type arguments
```

Code in question:

```rust
pub struct QueryRoot;

#[juniper::graphql_object(Context = Context)]
impl QueryRoot {
    fn sensors(context: &Context) -> Vec<Sensor> {
        use crate::schema::sensors::dsl::*;
        let connection = context.db.get().unwrap();
        sensors
            .limit(100)
            .load::<Sensor>(&connection)
            .expect("Error loading sensors")
    }
}

#[juniper::graphql_object(Context = Context)]
impl MutationRoot {
  fn create_sensor(context: &Context, data: NewSensor) -> Sensor {
    let connection = context.db.get().unwrap();
    diesel::insert_into(sensors::table)
        .values(&data)
        .get_result(&connection)
        .expect("Error saving new sensor")
  }
}

pub type Schema = RootNode<'static, QueryRoot, MutationRoot>;

pub fn create_schema() -> Schema {
    Schema::new(QueryRoot {}, MutationRoot {})
}
```
I've also tried using an EmptyMutation and DefaultScalar values and continue to receive errors. (I also get the impression the DefaultScalar doesn't implement support for UUID?)

```rust
pub type Schema = RootNode<'static, QueryRoot, EmptyMutation>;

pub fn create_schema() -> Schema {
    Schema::new(QueryRoot {}, EmptyMutation::<()>::new())
}
```

Any help would be tremendously appreciated.

**Comment by LegNeato** [comment]
Hello, welcome to Juniper and Rust! 🎉  Feel free to open issues for questions here whenever you have them.

I believe you are looking at docs for the latest release (which is on crates.io) but your code is pointed at `master`. On `master`, we have added subscriptions so there are three types to a schema:

```rust
type Schema = juniper::RootNode<'static, Query, EmptyMutation<()>, EmptySubscription<()>>;
```
(Note the added `EmptySubscription` type).

The master book can be seen here and is tested as part of CI so the examples should be current / correct for `master`:

https://graphql-rust.github.io/juniper/master/quickstart.html

Let me know if that fixes your issue! 🍻

**Comment by jaythomas** [comment]
Thank you for the warm welcome, and that was definitely my problem! I was looking at the wrong documentation and in hindsight it should have been obvious to check I was looking at the correct function signature.

As a side not, it seems the async changes on master have created an issue with uuid support. Maybe just a false alarm and I'm doing something wrong but wanted to point it out in case I should create an issue for it:

```rust
#[juniper::graphql_object(Context = Context, description = "Description for my table")]
impl Sensor {
    pub fn id(&self) -> Uuid {
        self.id
    }
    pub fn label(&self) -> &str {
        self.label.as_str()
    }
}
```

This code generated the error:
```
the trait bound `uuid::Uuid: juniper::GraphQLValueAsync` is not satisfied: the trait `juniper::GraphQLValueAsync` is not implemented for `uuid::Uuid`
```

Thanks again.

**Comment by LegNeato** [comment]
Ah, darn. I'll hopefully take a look tonight!

**Comment by LegNeato** [comment]
Hmm, something might be wonky with your setup or there is something else going on. Does running `cargo upgrade` fix it?

The following test works for me on latest `master`:

```rust
    #[test]
    fn used_as_field() {
        struct Query;

        #[graphql_object]
        impl Query {
            fn foo(&self) -> Uuid {
                Uuid::new_v4()
            }
            async fn bar(&self) -> Uuid {
                Uuid::new_v4()
            }
        }
        type Schema = RootNode<'static, Query, EmptyMutation<()>, EmptySubscription<()>>;
        let _ = Schema::new(Query, EmptyMutation::new(), EmptySubscription::new());
    }
```

Note that it is testing both async and sync fields.

**Comment by jaythomas** [comment]
I've pushed up the [full source](https://gitlab.com/jay-thomas/weather-station/-/tree/a6f67acb0ab45765216d4e48b23d023c493aec89/server) where the problem can be reproduced. Under `src/graphql_schema.rs` I have the line that can be uncommented:
```rust
pub type Schema = RootNode<'static, QueryRoot, EmptyMutation<Context>, EmptySubscription<()>>
```
Weather I use my MutationRoot or the EmptyMutation I receive complaints about Uuid. Could it be the version of the uuid crate my lock file uses is incorrect?

**Comment by LegNeato** [comment]
Ok, I poked at this a bit. I am not sure what is going on, but the error I am getting with a fresh checkout is from diesel not juniper. Even making diesel and juniper use the same uuid I can't get it to work, but I also don't have a ton of time right now and have never used diesel.

I started to try to fix it but had to stop as I was rewriting it and don't know much about your project 😄 .

I think it would be easiest for you to leverage `juniper_actix`. It handles a lot of the plumbing between `actix` and `juniper` for you. We have an example that works and you can start from:

https://github.com/graphql-rust/juniper/blob/master/juniper_actix/examples/actix_server.rs

As an aside, you also appear to be using  the old `futures-1.0`-style return values (that is, `Future<Item = X, Error = Y>` ) but all your dependencies in the `Cargo.toml` are `futures->=3.0`. That version only has one `Output` type instead of `Item` and `Error`....so you must have been following an old tutorial or copying old code.

Additionally, you might consider leveraging https://docs.rs/tokio-util/0.3.1/tokio_util/codec/struct.Framed.html for the udp portion of your server (assuming you want a fixed-sized frame to read).

I would highly suggest you starting with an exact copy of the `juniper-actix` example above, making sure it works (it should, file a bug if not!) and then layering on your other stuff one piece at a time. Make sure each piece works and then add some more. If you get to a point where you add stuff and it breaks and can't figure it out, please feel free to open a new issue (even if it is not related to Juniper) and I am happy to help!

**Comment by jaythomas** [comment]
Sorry to hear you had to wade through that code as that wasn't my intention for you to have to invest the time into that. To clarify, the juniper errors only appear in my code if you attempt to use EmptyMutation and EmptySubscription. (Needs to be uncommented in src/graphql_schema.rs):
```rust
pub type Schema = RootNode<'static, QueryRoot, EmptyMutation<Context>, EmptySubscription<()>>
```
If you say this error is an implementation issue on my end then that is fine too. I just wanted to verify there wasn't a legitimate bug that needed to be reported here. I will take a look at `juniper_actix` per your recommendation though. Thanks again for all the help!
