### ISSUE TITLE
Int scalar type compatility

### ISSUE THREAD

**Issue by daschdev** [graphql-rust/juniper#967]
Hi 👋🏻 

In my case, i'm using MongoDB and it uses i64 to count the records in a document ([https://prnt.sc/1doidmq](https://prnt.sc/1doidmq)) and juniper uses i32 for the Int scalar type, so I have problems with the compatibility between both types.

Looking at the code, the Float type uses `f64` and Int uses `i32` ([https://github.com/graphql-rust/juniper/blob/master/juniper/src/types/scalars.rs#L291](https://github.com/graphql-rust/juniper/blob/master/juniper/src/types/scalars.rs#L291)) , is there any reason or can it be changed to `i64`?

**Comment by tyranron** [comment]
@daschdev yes, the reason is the [GraphQL spec](https://spec.graphql.org/June2018/), which [declares `Int` as following](https://spec.graphql.org/June2018/#sec-Int):
> The `Int` scalar type represents a signed 32‐bit numeric non‐fractional value. Response formats that support a 32‐bit integer or a number type should use that type to represent this scalar.

So, either use `TryFrom` conversion from `i64` to `i32`, or roll out your [custom scalar](https://graphql-rust.github.io/juniper/master/types/scalars.html#custom-scalars), backed by `i64`. Doing the later, beware that JSON and JS still imply integers as `i32`, not `i64`, so your custom scalar should be able to parse from/into string.

**Comment by tyranron** [comment]
I'm closing this, as there is nothing we can do from our side. Feel free to reopen if needed.
